#!/bin/sh

RED="\033[1;31m"
BROWN="\033[1;33m"
GREEN="\033[1;32m"
NC="\033[0m"

linter_exit_code=1
tsc_exit_code=1
staged_ts_files=$(git diff --cached --diff-filter=d --name-only | grep -E "(.ts$|.tsx$)")

if [ -n $staged_ts_files ]
  then
    echo "${BROWN} 🥺 No .ts | .tsx files, skipping checks${NC}"
    exit 0
fi

echo "👀 Checking ESLint..."

./node_modules/.bin/eslint $staged_ts_files --quiet --fix
linter_exit_code=$?

if [ $linter_exit_code -ne 0 ]
  then
    echo "${RED} ❌ ESLint${NC}"
  else
    echo "${GREEN} ✔ ESLint${NC}"
fi

echo "👀 Checking Typescript..."

./node_modules/.bin/tsc || exit 0
tsc_exit_code=$?

if [ $tsc_exit_code -ne 0 ]
  then
    echo "${RED} ❌ Typescript${NC}"
  else
    echo "${GREEN} ✔ Typescript${NC}"
fi

if [ $linter_exit_code == 0 && $tsc_exit_code == 0 ]
  then
    echo "${GREEN} ✔ Files added to staging!${NC}"
    git add -f $staged_ts_files
    exit 0
  else
    exit 1
fi