#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm audit --audit-level=moderate

exit_code=$?

if [ "$exit_code" -ne "0" ] ; then
  echo "npm audit failed"
  echo "npm audit output:"
  exit 1
else
  echo "✅ npm audit passed"
fi

npx lint-staged --concurrent true
