#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn audit --audit-level=moderate

# exit_code=$?

# if [ "$exit_code" -ne "0" ] ; then
#   echo "yarn audit failed"
#   echo "yarn audit output:"
#   exit 1
# else
#   echo "✅ yarn audit passed"
# fi

echo "yarn audit skipped!"

npx lint-staged --concurrent true
